- hosts: all

  tasks:

        - name: Installation de l'agent Zabbix
          package:
                  name: zabbix-agent
                  state: present

        - name: Configuration de l'agent zabbix
          template:
                   src: PAA2022_zabbixagent.conf
                   dest: /etc/zabbix/zabbix_agentd.conf

          notify: Redemarrer-agent
        
        - name: Demarrage service zabbix-agent
          service:
                  name: zabbix-agent
                  state: started

  handlers:
            - name: Redemarrer-agent
              service:
                      name: zabbix-agent
                      state: restarted
