- hosts: all

  tasks:

        - name: Installation de l'agent Zabbix
          package:
                  name: zabbix-agent
                  state: present

        - name: Configuration de l'agent zabbix
          template:
                   src: zabbixagent.conf
                   dest: /etc/zabbix/zabbix_agentd.conf


          notify: Redemarrer-agent

  handlers:
            - name: Redemarrer-agent
              service:
                      name: zabbix-agent
                      state: restarted
